theme: jekyll-theme-cayman

title: A Primer on Applied Statistics
description: A user-friendly set of tutorials/FAQs for applied statistics, with a focus on psychology research.
github:
  is_project_page: false
